name: Cek Domain Kominfo

on:
  schedule:
    - cron: "*/5 * * * *"     # Setiap 5 menit
  workflow_dispatch:           # Bisa juga dijalankan manual

jobs:
  run-checker:
    runs-on: ubuntu-latest
    env:                        
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Jalankan pengecekan domain
        run: python cek_domain.py
